# Generated by Django 5.2 on 2025-05-20 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='driving_license',
        ),
    ]
